"""Initial Migration

Revision ID: 73207f30e741
Revises: 
Create Date: 2024-10-17 11:02:53.403518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73207f30e741'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.Enum('USER', 'RETAILER', name='usertype'), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tax_id')
    )
    op.create_table('wallet',
    sa.Column('id_wallet', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_wallet')
    )
    op.create_table('balance_history',
    sa.Column('id_history', sa.Integer(), nullable=False),
    sa.Column('wallet_id', sa.Integer(), nullable=False),
    sa.Column('change_amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id_wallet'], ),
    sa.PrimaryKeyConstraint('id_history')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('balance_history')
    op.drop_table('wallet')
    op.drop_table('user')
    # ### end Alembic commands ###
